---
- name: Download latest MongoDB
  uri:
    url: "https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/RPMS/{{ mongo_latest_rpm | trim }}"
    dest: "{{ role_path }}/files/mongodb/{{ mongo_latest_rpm | trim }}"
    creates: "{{ role_path }}/files/mongodb/{{ mongo_latest_rpm | trim }}"
    force: true
    mode: 0644
    owner: ansible
    group: ansible
  delegate_to: localhost
