---
- name: Download latest Omada Controller Software
  uri:
    url: "{{ omada_latest_link }}"
    dest: "{{ role_path }}/files/omada/{{ omada_latest_tgz | trim }}"
    creates: "{{ role_path }}/files/omada/{{ omada_latest_tgz | trim }}"
    force: true
    mode: 0644
    owner: ansible
    group: ansible
  delegate_to: localhost
