---
# tasks file for deploy-omada
#- name: Install necessary packages for Omada Controller
#  package: 
#    name: "{{ item }}" 
#    state: present
#  with_items:
#  - curl
#  - java-1.8.0-openjdk.x86_64
#  - java-1.8.0-openjdk-headless.x86_64
#  - java-11-openjdk-devel.x86_64
#  - java-11-openjdk-headless.x86_64
#  - java-11-openjdk.x86_64
#  - gcc
#  - make
#  - autoconf

- name: Get installed versions on system
  package_facts:
    manager: auto


- name: Create Directory for files inside Role Directory
  file:
    path: "{{ role_path }}/files"
    state: directory
    owner: ansible
    group: ansible
  delegate_to: localhost


- name: Check for various files/directories to see if they exists
  stat:
    path: "{{ role_path }}/files/{{ item }}"
  register: dir_data
  with_items:
  - mongodb
  - jsvc
  - omada
  delegate_to: localhost

- name: Check if Omada is currently installed
  stat:
    path: "/usr/bin/tpeap"
  register: tpeap_stat


- name: Get Latest Mongo RPM URL contents
  uri:
    url: https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/RPMS
    return_content: yes
  register: mongo_url_output
  delegate_to: localhost

- name: Set latest MongoDB Version Number
  set_fact:
    mongo_latest_rpm: "{{ mongo_url_output.content | regex_findall('.*(mongodb-org-server-[0-9]+\\.[0-9]+\\.[0-9]+\\-[0-9]+.*\\.rpm).*') | community.general.version_sort | last }}"
  

- name: Get Latest JSVC Commons Daemon URL contents
  uri:
    url: https://dlcdn.apache.org/commons/daemon/source
    return_content: yes
  register: jsvc_url_output
  delegate_to: localhost

- name: Set JSVC Facts
  set_fact:
    jsvc_latest_src: "{{jsvc_url_output.content | regex_findall('.*(commons-daemon-[0-9]+\\.[0-9]+\\.[0-9]+\\-src\\.tar\\.gz).*') | community.general.version_sort | last }}"

- name: Set JSVC Web Version
  set_fact:
    jsvc_latest_ver: "{{ jsvc_latest_src | regex_findall('.*([0-9]+\\.[0-9]+\\.[0-9]+).*') | last }}"


- name: Download latest MongoDB v4 - Dir Does Not Exist
  block:
  - name: Notify User MongoDB directory does not exist
    debug:
      msg: "Directory files/mongodb does not exist.  Will need to download latest supported MongoDB"
    delegate_to: localhost

  - name: Create Directory for MongoDB files
    file:
      path: "{{ role_path }}/files/mongodb"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest MongoDB for Initialization
    import_tasks: download-latest-mongodb.yml
  when: ( not dir_data.results[0].stat.exists )


- name: Download latest JSVC - Dir Does Not Exist
  block:
  - name: Determine if jsvc directory exists
    debug:
      msg: "Directory files/jsvc does not exist.  Will need to download latest supported jsvc"
    delegate_to: localhost

  - name: Create Directory for JSVC files
    file:
      path: "{{ role_path }}/files/jsvc"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest JSVC for Initialization
    import_tasks: download-latest-jsvc.yml
  when: ( not dir_data.results[1].stat.exists )


- name: Download latest Omada Controller Software - Dir Does Not Exist
  block:
  - name: Determine if Omada directory exists
    debug:
      msg: "Directory files/omada does not exist.  Will need to download latest supported Omada Controller Software"
    delegate_to: localhost

  - name: Create Directory for Omada files
    file:
      path: "{{ role_path }}/files/omada"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest Omada Software as of 30 December 2022
    import_tasks: download-latest-omada.yml
  when: ( not dir_data.results[2].stat.exists )


- name: Update MongoDB
  import_tasks: update-mongodb.yml

- name: update JSVC
  import_tasks: update-jsvc.yml

- name: Update Omada Controller Software
  import_tasks: update-omada.yml

- name: Notify User no automatic download of Omada Controller Software
  debug:
    msg:  "Unfortunately at this time, there is no way to automatically download the latest Omada \nController Software.  This role is hard coded to download 5.7.4 from a static link.  \nIf there is a newer version, place the latest TARBALL into {{ role_path }}/files/omada and this role \nwill automatically install the software if it is newer than the currently installed version on your Omada Server."

