---
# tasks file for deploy-omada
- name: Install necessary packages for Omada Controller
  package: 
    name: "{{ item }}" 
    state: present
  with_items:
  - curl
  - java-1.8.0-openjdk.x86_64
  - java-1.8.0-openjdk-headless.x86_64
  - java-11-openjdk-devel.x86_64
  - java-11-openjdk-headless.x86_64
  - java-11-openjdk.x86_64
  - gcc
  - make
  - autoconf

- name: Get installed versions on system
  package_facts:
    manager: auto


- name: Create Directory for files inside Role Directory
  file:
    path: "{{ role_path }}/files"
    state: directory
    owner: ansible
    group: ansible
  delegate_to: localhost


- name: Check for various files/directories to see if they exists
  stat:
    path: "{{ role_path }}/files/{{ item }}"
  register: dir_data
  with_items:
  - mongodb
  - jsvc
  - omada
  delegate_to: localhost

- name: Check if Omada is currently installed
  stat:
    path: "/usr/bin/tpeap"
  register: tpeap_stat


- name: Get Latest Mongo RPM URL contents
  uri:
    url: https://repo.mongodb.org/yum/redhat/8/mongodb-org/4.4/x86_64/RPMS
    return_content: yes
  register: mongo_url_output
  delegate_to: localhost

- name: Set latest MongoDB Version Number
  set_fact:
    mongo_latest_rpm: "{{ mongo_url_output.content | regex_findall('.*(mongodb-org-server-[0-9]+\\.[0-9]+\\.[0-9]+\\-[0-9]+.*\\.rpm).*') | community.general.version_sort | last }}"
  

- name: Get Latest JSVC Commons Daemon URL contents
  uri:
    url: https://dlcdn.apache.org/commons/daemon/source
    return_content: yes
  register: jsvc_url_output
  delegate_to: localhost

- name: Set JSVC Facts
  set_fact:
    jsvc_latest_src: "{{jsvc_url_output.content | regex_findall('.*(commons-daemon-[0-9]+\\.[0-9]+\\.[0-9]+\\-src\\.tar\\.gz).*') | community.general.version_sort | last }}"

- name: Set JSVC Web Version
  set_fact:
    jsvc_latest_ver: "{{ jsvc_latest_src | regex_findall('.*([0-9]+\\.[0-9]+\\.[0-9]+).*') | last }}"


- name: Get Latest Omada Controller Software URL Contents
  uri:
    url: https://www.tp-link.com/us/support/download/omada-software-controller
    return_content: yes
  register: omada_url_output
  delegate_to: localhost

- name: Set latest MongoDB Version download URL
  set_fact:
    omada_latest_link: "{{ omada_url_output.content | regex_findall('.*(https://.*Omada_SDN_Controller_v[0-9]+\\.[0-9]+\\.[0-9]+.*\\.tar.gz).*') | community.general.version_sort | last }}"

- name: Set latest MongoDB Version download URL
  set_fact:
    omada_latest_tgz: "{{ omada_url_output.content | regex_findall('.*(Omada_SDN_Controller_v[0-9]+\\.[0-9]+\\.[0-9]+.*\\.tar.gz).*') | community.general.version_sort | last }}"


- name: Download latest MongoDB v4 - Dir Does Not Exist
  block:
  - name: Notify User MongoDB directory does not exist
    debug:
      msg: "Directory files/mongodb does not exist.  Will need to download latest supported MongoDB"
    delegate_to: localhost

  - name: Create Directory for MongoDB files
    file:
      path: "{{ role_path }}/files/mongodb"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest MongoDB for Initialization
    import_tasks: download-latest-mongodb.yml
  when: ( not dir_data.results[0].stat.exists )


- name: Download latest JSVC - Dir Does Not Exist
  block:
  - name: Determine if jsvc directory exists
    debug:
      msg: "Directory files/jsvc does not exist.  Will need to download latest supported jsvc"
    delegate_to: localhost

  - name: Create Directory for JSVC files
    file:
      path: "{{ role_path }}/files/jsvc"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest JSVC for Initialization
    import_tasks: download-latest-jsvc.yml
  when: ( not dir_data.results[1].stat.exists )


- name: Download latest Omada Controller Software - Dir Does Not Exist
  block:
  - name: Determine if Omada directory exists
    debug:
      msg: "Directory files/omada does not exist.  Will need to download latest supported Omada Controller Software"
    delegate_to: localhost

  - name: Create Directory for Omada files
    file:
      path: "{{ role_path }}/files/omada"
      state: directory
      owner: ansible
      group: ansible
    delegate_to: localhost

  - name: Download latest Omada Software
    import_tasks: download-latest-omada.yml
  when: ( not dir_data.results[2].stat.exists )


### Update Programs As Needed ###
- name: Update MongoDB
  import_tasks: update-mongodb.yml

- name: update JSVC
  import_tasks: update-jsvc.yml

- name: Update Omada Controller Software
  import_tasks: update-omada.yml

### Debug Information ###
- name: Debug information for MongoDB
  debug:
    msg: "Newest MongoDB Version: {{ mongo_latest_ver }} \nInstalled MongoDB Version: {{ mongo_sys_ver }}"

- name: Debug information for JSVC
  debug:
    msg: "Newest JSVC Version: {{ jsvc_latest_ver }} \nInstalled JSVC Version: {{ jsvc_sys_ver }}"

- name: Debug information for Omada
  debug:
    msg: "Newest Omada Version: {{ omada_latest_ver }} \nInstalled Omada Version: {{ omada_sys_ver }}"


